### ISSUE TITLE
ilog behaves differently from std lib

### ISSUE THREAD

**Issue by chipshort** [isaacholt100/bnum#39]
The unchecked `ilog*` functions in the std crate [always panic for inputs <= 0](https://doc.rust-lang.org/std/primitive.u128.html#panics-2), even in release mode (see also this [playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=a8c5aa3278ea969d5b0f623563bea848)), while the implementation in here [only panics in debug mode](https://github.com/isaacholt100/bnum/blob/f1520e5aadcac29983299d48465b785629389702/src/buint/mod.rs#L298) and returns 0 in release mode.

If this is unintended, I'd be happy to open a PR to behave like the Rust primitives.

**Comment by isaacholt100** [comment]
Hi @chipshort, thanks for spotting this and opening the issue! I have now fixed this, and additionally I have made the panic message match that of Rust's primitives. I think I originally wrote these functions when the primitive `ilog*` methods were unstable, so their behaviour must have changed since then. I've pushed these changes to the `latest` branch, will merge with master and publish to `v0.11.0` soon.

**Comment by chipshort** [comment]
Thanks for the quick fix!

**Comment by isaacholt100** [comment]
@chipshort I've just published v0.11.0, sorry this took a bit of time to actually get done, it's very busy last few weeks!

**Comment by chipshort** [comment]
No need to appologize. Thanks for creating and maintaining this library!
